// UI 文案表：全部界面字符串按语言集中于此（纯数据 + 少量格式化函数，无副作用）。
// 纯逻辑层的文案不在这里——它们各自带译文、按显式注入的 locale 输出（见 src/i18n/locale.ts）。
// 品牌名遵循 ADR-0002：中文「准时」，英文 "Zhunshi"。

import { type Locale } from '../i18n/locale';

const zh = {
  // 通用
  back: '‹ 返回',
  cancel: '取消',
  save: '保存',
  delete: '删除',

  // 首页
  brand: '准时',
  headerDate: (month: number, day: number, weekday: number): string =>
    `${month} 月 ${day} 日 · 周${'日一二三四五六'[weekday]}`,
  upNext: '接下来',
  newSequential: '＋ 顺序',
  newScheduled: '＋ 日程',
  aiGenerate: '✨ AI 生成',
  importAction: '导入',
  backupAction: '备份',
  backupShareTitle: '准时 · 全库备份',
  backupOutcomeShared: '已唤起分享，把备份存到文件或发给自己 ✓',
  backupOutcomeCopied: '已复制备份数据，请粘贴保存到安全的地方 ✓',
  backupOutcomeUnavailable: '此环境不支持分享或剪贴板',
  backupFailed: '备份失败，请重试',
  deleteFailed: '删除未完成，请重试',
  catalogUnavailable: '本地数据暂时无法读取；为避免打开错误的流程，已暂停显示流程库。',
  retry: '重试',
  sectionMine: '我的',
  sectionExamples: '示例',
  cardMeta: (n: number, topology: 'sequential' | 'scheduled'): string =>
    `${n} ${topology === 'sequential' ? '步' : '个时刻'} · 点按运行`,
  linkInsight: '解读',
  linkEdit: '编辑',
  linkShare: '分享',

  // 运行（顺序型）
  runDone: '已完成',
  runTotalSteps: (n: number): string => `共 ${n} 步`,
  runStepOf: (i: number, n: number, paused: boolean): string =>
    `第 ${i} / ${n} 步${paused ? ' · 已暂停' : ''}`,
  runStartAnytime: '随时开始',
  runGateHint: '完成后确认',
  runInstantHint: '完成即过',
  runFlowFinished: '这条 flow 走完了',
  runTimeUp: '计时完成，可进入下一步',
  runStorageUnavailable: '进行中的运行记录暂时无法读取。为避免覆盖已有进度，已暂停运行。',
  runRestart: '重新开始',
  runStart: '开始',
  runConfirm: '确认',
  runCompleteStep: '完成本步',
  runPrev: '上一步',
  runResume: '恢复',
  runPause: '暂停',
  runSkip: '跳过',

  // Timeline 节点元信息
  nodeNeedsConfirm: '需确认',
  nodeInstant: '即时',

  // 日程视图（服药）
  doseUpcoming: '待服',
  doseDue: '可服用',
  doseTaken: '已服',
  doseMissed: '漏服',
  scheduleToday: (cadence: string, timeZone?: string): string =>
    `今天 · ${cadence}${timeZone ? ` · 按 ${timeZone} 时区` : ''}`,
  scheduleOffDay: (next: { month: number; day: number; time: string } | null): string =>
    `今天不在节律上${next ? `，下一次：${next.month} 月 ${next.day} 日 ${next.time}` : ''}。`,
  scheduleNow: (time: string): string => `现在 ${time}`,
  checkIn: '打卡',
  undo: '撤销',
  scheduleNote: '本表仅作提醒之用，不构成医疗处方或诊断；请以医嘱为准。',
  scheduleOnceNote: '这条 flow 仅提醒今天一次，过时不候；需要长期提醒，请在编辑里把重复改为每天/每周。',
  scheduleNotifDenied: '提醒未开启：通知权限被拒绝，到点不会有提醒。',
  scheduleNotifSettings: '去系统设置开启 ›',
  scheduleNotifWeb: '网页版不支持定时提醒；请在手机 App 上使用提醒功能。',
  scheduleStorageUnavailable: '打卡记录暂时无法读取。为避免覆盖已有记录，已暂停打卡。',
  scheduleSaving: '正在保存打卡记录，尚未确认成功…',
  scheduleSaveFailed: '打卡未确认保存。记录可能未写入，请重试；不会把未确认记录显示为成功。',
  scheduleUnsavedTitle: '打卡尚未确认保存',
  scheduleUnsavedExit: '离开后无法在此重试未确认的打卡。已接收的写入仍会完成，但可能失败。',
  scheduleLeaveAnyway: '仍然离开',

  // 编辑器
  editorTitle: '编辑',
  editorDiscardTitle: '放弃未保存的更改？',
  editorDiscardMessage: '这些更改还没有保存。',
  editorContinueEditing: '继续编辑',
  editorDiscardChanges: '放弃更改',
  editorSaving: '保存中…',
  editorInvalidCompactInput: '请完成或修正时长、时间或间隔输入。',
  editorFlowName: '流程名称',
  editorDescription: '一句话描述（可选）',
  editorTimeZone: '锚定时区（可选，如 Asia/Shanghai；留空跟随设备）',
  editorRepeat: '重复',
  editorWeekdaysLabel: '星期',
  editorEveryNDays: '间隔(天)',
  editorSectionScheduled: '定时事件',
  editorSectionSteps: '步骤',
  editorKindTimed: '计时',
  editorKindGate: '确认',
  editorKindInstant: '瞬时',
  editorRepeatOnce: '仅今天',
  editorRepeatDaily: '每天',
  editorRepeatWeekly: '每周',
  editorRepeatEveryN: '隔 N 天',
  editorOnceHint: '「仅今天」过时不候：今天没提醒到，不会顺延到明天。需要长期提醒请选每天/每周/隔 N 天。',
  weekdayNames: ['日', '一', '二', '三', '四', '五', '六'],
  editorTime: '时间',
  editorDuration: '时长',
  editorDurationCustomSeconds: '自定义（秒）',
  editorDurationPreset30Sec: '30 秒',
  editorDurationPreset1Min: '1 分钟',
  editorDurationPreset5Min: '5 分钟',
  editorDurationPreset10Min: '10 分钟',
  editorDurationPreset30Min: '30 分钟',
  editorWaitLabel: '等待',
  editorWhy: '为什么（可选）',
  editorEventPlaceholder: '事件（如：早餐后服药）',
  editorStepPlaceholder: '这一步做什么',
  editorAddEvent: '＋ 添加事件',
  editorAddStep: '＋ 添加步骤',
  editorAddWait: '＋ 等待',
  editorMoveUp: '上移',
  editorMoveDown: '下移',
  editorDeleteNode: '删除',
  editorInvalidTimeZone: (name: string): string =>
    `时区名无效：${name}（应为 IANA 名，如 Asia/Shanghai）`,

  // 分享 / 导出
  exportTitle: '分享 · 导出',
  exportHint:
    '分享全文 = 一段人能读懂的做法说明 + 可导入的数据。对方把全文粘进「准时」的导入框，就收下了这条 flow。',
  exportAuthor: '署名（可选，随分享一起标注来源）',
  exportPreview: '预览',
  exportShareFull: '分享全文…',
  exportDataOnly: '仅数据（JSON）',
  exportShareData: '只分享数据',
  shareOutcomeShared: '已唤起分享 ✓',
  shareOutcomeCopied: '已复制全文，去粘贴给朋友吧 ✓',
  shareOutcomeUnavailable: '此环境不支持分享或剪贴板',

  // 导入
  importTitle: '导入',
  importHint: '把朋友分享的全文（或 flow 的 JSON、整库备份）粘贴到下面，导入到你的库。',
  importNotFound: '没有找到可导入的 flow 数据，请粘贴分享全文或 JSON',
  importConfirm: '确认导入',
  importBusy: '导入中…',
  importBackupDetected: (n: number): string =>
    `检测到整库备份：${n} 条 flow。历史修订与打卡记录将一并恢复，不覆盖本机数据。`,

  // AI 助手（解读/洞察/差异）
  insightTitle: 'AI 助手',
  insightReading: '解读',
  insightFindings: '洞察',
  insightNoFindings: '没有发现明显问题 👍',
  insightDiffTitle: (version: number): string => `与上一版（v${version}）的差异`,
  insightNoDiff: '与上一版没有差异。',
  insightRestore: '回到上一版',
  insightNote: '以上由本地解释器生成，不含真实模型。AI 永远只提议与解释，改动由你决定、可回退。',

  // AI 生成
  generateTitle: 'AI 生成',
  generateHint: '用一句话描述你的时间模式，AI 会转写成一条 flow 草稿，由你审阅后保存。',
  generatePlaceholder: '例：法压咖啡——倒 92 度热水，浸泡 4 分钟，压下压杆再倒出',
  generateModelSettings: '模型设置',
  generateProviderOpenAI: 'OpenAI 兼容',
  generateBaseUrl: '端点（Base URL）',
  generateModel: '模型',
  generateModelPlaceholder: '如 deepseek-chat',
  generateApiKey: 'API Key（只保存在本机）',
  generateKeyOptional: '本地服务（Ollama）可留空',
  generateBusy: '生成中…',
  generateSubmit: '生成草稿',
  generateFootnote: '生成后会进入编辑器，确认无误再保存；保存即产生可回退的新版本。',
};

export type Strings = typeof zh;

// 繁体（zh-Hant）：用词按台湾/香港惯例（儲存、匯入/匯出、設定、裝置、資料）。
const zhHant: Strings = {
  back: '‹ 返回',
  cancel: '取消',
  save: '儲存',
  delete: '刪除',

  brand: '準時',
  headerDate: (month, day, weekday) =>
    `${month} 月 ${day} 日 · 週${'日一二三四五六'[weekday]}`,
  upNext: '接下來',
  newSequential: '＋ 順序',
  newScheduled: '＋ 日程',
  aiGenerate: '✨ AI 生成',
  importAction: '匯入',
  backupAction: '備份',
  backupShareTitle: '準時 · 全庫備份',
  backupOutcomeShared: '已喚起分享，把備份存到檔案或傳給自己 ✓',
  backupOutcomeCopied: '已複製備份資料，請貼上保存到安全的地方 ✓',
  backupOutcomeUnavailable: '此環境不支援分享或剪貼簿',
  backupFailed: '備份失敗，請重試',
  deleteFailed: '刪除未完成，請重試',
  catalogUnavailable: '本機資料暫時無法讀取；為避免開啟錯誤的流程，已暫停顯示流程庫。',
  retry: '重試',
  sectionMine: '我的',
  sectionExamples: '範例',
  cardMeta: (n, topology) => `${n} ${topology === 'sequential' ? '步' : '個時刻'} · 點按執行`,
  linkInsight: '解讀',
  linkEdit: '編輯',
  linkShare: '分享',

  runDone: '已完成',
  runTotalSteps: (n) => `共 ${n} 步`,
  runStepOf: (i, n, paused) => `第 ${i} / ${n} 步${paused ? ' · 已暫停' : ''}`,
  runStartAnytime: '隨時開始',
  runGateHint: '完成後確認',
  runInstantHint: '完成即過',
  runFlowFinished: '這條 flow 走完了',
  runTimeUp: '計時完成，可進入下一步',
  runStorageUnavailable: '進行中的執行記錄暫時無法讀取。為避免覆蓋既有進度，已暫停執行。',
  runRestart: '重新開始',
  runStart: '開始',
  runConfirm: '確認',
  runCompleteStep: '完成本步',
  runPrev: '上一步',
  runResume: '繼續',
  runPause: '暫停',
  runSkip: '跳過',

  nodeNeedsConfirm: '需確認',
  nodeInstant: '即時',

  doseUpcoming: '待服',
  doseDue: '可服用',
  doseTaken: '已服',
  doseMissed: '漏服',
  scheduleToday: (cadence, timeZone) =>
    `今天 · ${cadence}${timeZone ? ` · 按 ${timeZone} 時區` : ''}`,
  scheduleOffDay: (next) =>
    `今天不在節律上${next ? `，下一次：${next.month} 月 ${next.day} 日 ${next.time}` : ''}。`,
  scheduleNow: (time) => `現在 ${time}`,
  checkIn: '打卡',
  undo: '復原',
  scheduleNote: '本表僅作提醒之用，不構成醫療處方或診斷；請以醫囑為準。',
  scheduleOnceNote: '這條 flow 僅提醒今天一次，過時不候；需要長期提醒，請在編輯裡把重複改為每天/每週。',
  scheduleNotifDenied: '提醒未開啟：通知權限被拒絕，到點不會有提醒。',
  scheduleNotifSettings: '去系統設定開啟 ›',
  scheduleNotifWeb: '網頁版不支援定時提醒；請在手機 App 上使用提醒功能。',
  scheduleStorageUnavailable: '打卡記錄暫時無法讀取。為避免覆蓋既有記錄，已暫停打卡。',
  scheduleSaving: '正在儲存打卡記錄，尚未確認成功…',
  scheduleSaveFailed: '打卡尚未確認儲存。記錄可能未寫入，請重試；不會把未確認記錄顯示為成功。',
  scheduleUnsavedTitle: '打卡尚未確認儲存',
  scheduleUnsavedExit: '離開後無法在此重試未確認的打卡。已接受的寫入仍會完成，但可能失敗。',
  scheduleLeaveAnyway: '仍然離開',

  editorTitle: '編輯',
  editorDiscardTitle: '放棄未儲存的變更？',
  editorDiscardMessage: '這些變更還沒有儲存。',
  editorContinueEditing: '繼續編輯',
  editorDiscardChanges: '放棄變更',
  editorSaving: '儲存中…',
  editorInvalidCompactInput: '請完成或修正時長、時間或間隔輸入。',
  editorFlowName: '流程名稱',
  editorDescription: '一句話描述（可選）',
  editorTimeZone: '錨定時區（可選，如 Asia/Taipei；留空跟隨裝置）',
  editorRepeat: '重複',
  editorWeekdaysLabel: '星期',
  editorEveryNDays: '間隔(天)',
  editorSectionScheduled: '定時事件',
  editorSectionSteps: '步驟',
  editorKindTimed: '計時',
  editorKindGate: '確認',
  editorKindInstant: '瞬時',
  editorRepeatOnce: '僅今天',
  editorRepeatDaily: '每天',
  editorRepeatWeekly: '每週',
  editorRepeatEveryN: '隔 N 天',
  editorOnceHint: '「僅今天」過時不候：今天沒提醒到，不會順延到明天。需要長期提醒請選每天/每週/隔 N 天。',
  weekdayNames: ['日', '一', '二', '三', '四', '五', '六'],
  editorTime: '時間',
  editorDuration: '時長',
  editorDurationCustomSeconds: '自訂（秒）',
  editorDurationPreset30Sec: '30 秒',
  editorDurationPreset1Min: '1 分鐘',
  editorDurationPreset5Min: '5 分鐘',
  editorDurationPreset10Min: '10 分鐘',
  editorDurationPreset30Min: '30 分鐘',
  editorWaitLabel: '等待',
  editorWhy: '為什麼（可選）',
  editorEventPlaceholder: '事件（如：早餐後服藥）',
  editorStepPlaceholder: '這一步做什麼',
  editorAddEvent: '＋ 新增事件',
  editorAddStep: '＋ 新增步驟',
  editorAddWait: '＋ 等待',
  editorMoveUp: '上移',
  editorMoveDown: '下移',
  editorDeleteNode: '刪除',
  editorInvalidTimeZone: (name) => `時區名無效：${name}（應為 IANA 名，如 Asia/Taipei）`,

  exportTitle: '分享 · 匯出',
  exportHint:
    '分享全文 = 一段人能讀懂的做法說明 + 可匯入的資料。對方把全文貼進「準時」的匯入框，就收下了這條 flow。',
  exportAuthor: '署名（可選，隨分享一起標註來源）',
  exportPreview: '預覽',
  exportShareFull: '分享全文…',
  exportDataOnly: '僅資料（JSON）',
  exportShareData: '只分享資料',
  shareOutcomeShared: '已喚起分享 ✓',
  shareOutcomeCopied: '已複製全文，去貼給朋友吧 ✓',
  shareOutcomeUnavailable: '此環境不支援分享或剪貼簿',

  importTitle: '匯入',
  importHint: '把朋友分享的全文（或 flow 的 JSON、整庫備份）貼到下面，匯入到你的庫。',
  importNotFound: '沒有找到可匯入的 flow 資料，請貼上分享全文或 JSON',
  importConfirm: '確認匯入',
  importBusy: '匯入中…',
  importBackupDetected: (n) => `偵測到整庫備份：${n} 條 flow。歷史修訂與打卡記錄將一併恢復，不覆蓋本機資料。`,

  insightTitle: 'AI 助手',
  insightReading: '解讀',
  insightFindings: '洞察',
  insightNoFindings: '沒有發現明顯問題 👍',
  insightDiffTitle: (version) => `與上一版（v${version}）的差異`,
  insightNoDiff: '與上一版沒有差異。',
  insightRestore: '回到上一版',
  insightNote: '以上由本機解讀器產生，不含真實模型。AI 永遠只提議與解釋，改動由你決定、可復原。',

  generateTitle: 'AI 生成',
  generateHint: '用一句話描述你的時間模式，AI 會轉寫成一條 flow 草稿，由你審閱後儲存。',
  generatePlaceholder: '例：法壓咖啡——倒 92 度熱水，浸泡 4 分鐘，壓下壓桿再倒出',
  generateModelSettings: '模型設定',
  generateProviderOpenAI: 'OpenAI 相容',
  generateBaseUrl: '端點（Base URL）',
  generateModel: '模型',
  generateModelPlaceholder: '如 deepseek-chat',
  generateApiKey: 'API Key（只儲存在本機）',
  generateKeyOptional: '本機服務（Ollama）可留空',
  generateBusy: '生成中…',
  generateSubmit: '生成草稿',
  generateFootnote: '生成後會進入編輯器，確認無誤再儲存；儲存即產生可復原的新版本。',
};

const en: Strings = {
  back: '‹ Back',
  cancel: 'Cancel',
  save: 'Save',
  delete: 'Delete',

  brand: 'Zhunshi',
  headerDate: (month, day, weekday) =>
    `${['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'][weekday]}, ${['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'][month - 1]} ${day}`,
  upNext: 'UP NEXT',
  newSequential: '＋ Sequence',
  newScheduled: '＋ Schedule',
  aiGenerate: '✨ AI draft',
  importAction: 'Import',
  backupAction: 'Backup',
  backupShareTitle: 'Zhunshi · Full backup',
  backupOutcomeShared: 'Share sheet opened — save the backup to a file or send it to yourself ✓',
  backupOutcomeCopied: 'Backup copied — paste it somewhere safe ✓',
  backupOutcomeUnavailable: 'Sharing and clipboard are unavailable here',
  backupFailed: 'Backup failed; retry',
  deleteFailed: 'Deletion did not finish; retry',
  catalogUnavailable: 'Local data is temporarily unavailable. The catalog is hidden to avoid opening the wrong flow.',
  retry: 'Retry',
  sectionMine: 'MINE',
  sectionExamples: 'EXAMPLES',
  cardMeta: (n, topology) =>
    `${n} ${topology === 'sequential' ? (n === 1 ? 'step' : 'steps') : n === 1 ? 'time' : 'times'} · tap to run`,
  linkInsight: 'Insight',
  linkEdit: 'Edit',
  linkShare: 'Share',

  runDone: 'Done',
  runTotalSteps: (n) => `${n} ${n === 1 ? 'step' : 'steps'}`,
  runStepOf: (i, n, paused) => `Step ${i} of ${n}${paused ? ' · paused' : ''}`,
  runStartAnytime: 'Start anytime',
  runGateHint: 'Confirm when done',
  runInstantHint: 'Tap when done',
  runFlowFinished: 'This flow is complete',
  runTimeUp: "Time's up — continue when ready",
  runStorageUnavailable: 'The active run could not be read. Running is paused to avoid overwriting saved progress.',
  runRestart: 'Restart',
  runStart: 'Start',
  runConfirm: 'Confirm',
  runCompleteStep: 'Complete step',
  runPrev: 'Previous',
  runResume: 'Resume',
  runPause: 'Pause',
  runSkip: 'Skip',

  nodeNeedsConfirm: 'confirm',
  nodeInstant: 'instant',

  doseUpcoming: 'Upcoming',
  doseDue: 'Due',
  doseTaken: 'Taken',
  doseMissed: 'Missed',
  scheduleToday: (cadence, timeZone) =>
    `Today · ${cadence}${timeZone ? ` · in ${timeZone}` : ''}`,
  scheduleOffDay: (next) =>
    `Not on the cadence today${next ? `. Next: ${next.month}/${next.day} at ${next.time}` : ''}.`,
  scheduleNow: (time) => `Now ${time}`,
  checkIn: 'Check in',
  undo: 'Undo',
  scheduleNote:
    "This list is a reminder aid only — not a medical prescription or diagnosis. Follow your clinician's advice.",
  scheduleOnceNote:
    'This flow reminds you today only — it does not carry over to tomorrow. Edit its repeat to daily/weekly for ongoing reminders.',
  scheduleNotifDenied: 'Reminders are off: notification permission was denied, so nothing will fire on time.',
  scheduleNotifSettings: 'Enable in system settings ›',
  scheduleNotifWeb: 'The web version cannot deliver scheduled reminders — use the mobile app for reminders.',
  scheduleStorageUnavailable: 'Check-in history could not be read. Check-ins are paused to avoid overwriting saved records.',
  scheduleSaving: 'Saving check-in — not confirmed yet…',
  scheduleSaveFailed: 'Check-in not confirmed saved. The write may have failed; retry before relying on this record.',
  scheduleUnsavedTitle: 'Check-in not confirmed saved',
  scheduleUnsavedExit: 'Leaving prevents retrying this check-in here. Accepted writes will finish but may still fail.',
  scheduleLeaveAnyway: 'Leave anyway',

  editorTitle: 'Edit',
  editorDiscardTitle: 'Discard unsaved changes?',
  editorDiscardMessage: 'Your changes have not been saved.',
  editorContinueEditing: 'Keep editing',
  editorDiscardChanges: 'Discard changes',
  editorSaving: 'Saving…',
  editorInvalidCompactInput: 'Finish or correct the duration, time, or interval input.',
  editorFlowName: 'Flow name',
  editorDescription: 'One-line description (optional)',
  editorTimeZone: 'Anchor time zone (optional, e.g. Asia/Shanghai; blank = device)',
  editorRepeat: 'Repeat',
  editorWeekdaysLabel: 'Weekday',
  editorEveryNDays: 'Every (days)',
  editorSectionScheduled: 'TIMED EVENTS',
  editorSectionSteps: 'STEPS',
  editorKindTimed: 'Timed',
  editorKindGate: 'Confirm',
  editorKindInstant: 'Instant',
  editorRepeatOnce: 'Today only',
  editorRepeatDaily: 'Daily',
  editorRepeatWeekly: 'Weekly',
  editorRepeatEveryN: 'Every N days',
  editorOnceHint:
    '“Today only” does not carry over: if today passes, nothing moves to tomorrow. Choose daily / weekly / every N days for ongoing reminders.',
  weekdayNames: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  editorTime: 'Time',
  editorDuration: 'Duration',
  editorDurationCustomSeconds: 'Custom (seconds)',
  editorDurationPreset30Sec: '30 sec',
  editorDurationPreset1Min: '1 min',
  editorDurationPreset5Min: '5 min',
  editorDurationPreset10Min: '10 min',
  editorDurationPreset30Min: '30 min',
  editorWaitLabel: 'Wait',
  editorWhy: 'Why (optional)',
  editorEventPlaceholder: 'Event (e.g. morning pill)',
  editorStepPlaceholder: 'What happens in this step',
  editorAddEvent: '＋ Add event',
  editorAddStep: '＋ Add step',
  editorAddWait: '＋ Wait',
  editorMoveUp: 'Move up',
  editorMoveDown: 'Move down',
  editorDeleteNode: 'Delete',
  editorInvalidTimeZone: (name) =>
    `Invalid time zone: ${name} (use an IANA name like Asia/Shanghai)`,

  exportTitle: 'Share · Export',
  exportHint:
    'The full share text = a human-readable walkthrough plus importable data. Paste the whole text into Zhunshi\'s import box to receive the flow.',
  exportAuthor: 'Sign your name (optional, noted as the source)',
  exportPreview: 'PREVIEW',
  exportShareFull: 'Share full text…',
  exportDataOnly: 'DATA ONLY (JSON)',
  exportShareData: 'Share data only',
  shareOutcomeShared: 'Share sheet opened ✓',
  shareOutcomeCopied: 'Copied — paste it to a friend ✓',
  shareOutcomeUnavailable: 'Sharing and clipboard are unavailable here',

  importTitle: 'Import',
  importHint: "Paste a friend's shared text (or a flow's JSON, or a full backup) below to add it to your library.",
  importNotFound: 'No importable flow data found — paste the full share text or JSON',
  importConfirm: 'Import',
  importBusy: 'Importing…',
  importBackupDetected: (n) =>
    `Full backup detected: ${n} ${n === 1 ? 'flow' : 'flows'}. History and check-ins will be restored without overwriting local data.`,

  insightTitle: 'AI Assistant',
  insightReading: 'READING',
  insightFindings: 'INSIGHTS',
  insightNoFindings: 'No obvious issues found 👍',
  insightDiffTitle: (version) => `Changes since v${version}`,
  insightNoDiff: 'No changes from the previous version.',
  insightRestore: 'Restore previous version',
  insightNote:
    'Generated by the local interpreter — no external model involved. AI only proposes and explains; you decide, and changes can be undone.',

  generateTitle: 'AI Draft',
  generateHint: 'Describe your temporal pattern in a sentence; AI drafts a flow for you to review and save.',
  generatePlaceholder: 'e.g. French press — pour 92°C water, steep 4 minutes, press and pour',
  generateModelSettings: 'MODEL SETTINGS',
  generateProviderOpenAI: 'OpenAI-compatible',
  generateBaseUrl: 'Endpoint (Base URL)',
  generateModel: 'Model',
  generateModelPlaceholder: 'e.g. deepseek-chat',
  generateApiKey: 'API Key (stored only on this device)',
  generateKeyOptional: 'Optional for local services (Ollama)',
  generateBusy: 'Generating…',
  generateSubmit: 'Generate draft',
  generateFootnote: 'The draft opens in the editor; saving creates a new, restorable version.',
};

export const STRINGS: Record<Locale, Strings> = { zh, 'zh-Hant': zhHant, en };
